
description: "ICCV 2025 · Efficient long-video processing for VLMs"
remote_theme: pages-themes/cayman@v0.2.0   # any Pages theme works
plugins: [jekyll-remote-theme]             # required for remote_theme
markdown: kramdown
